server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/zinchen-ko/springConfigs
          clone-on-start: true
  security:
    user:
      name: admin
      password: admin